
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: actions.apps.quark.io
spec:
  group: apps.quark.io
  names:
    kind: Action
    listKind: ActionList
    plural: actions
    singular: action
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: The Schema for the Action API
          type: object
          properties:
            spec:
              description: ActionSpec defines action resource
              type: object
              properties:
                notifyAction:
                  type: string
                notifyType:
                  type: string
                resourceType:
                  type: string
                notifyRetInfo:
                  type: string
                resources:
                  type: array
                  items:
                    type: object
                    properties:
                      ID:
                        type: string
                      resourceType:
                        type: string
                extra: # map[string]string
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
            status:
              description: Defines the observed state of Action
              type: object
              properties:
                status:
                  description: The Action status.
                  type: string