
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: networks.apps.quark.io
spec:
  group: apps.quark.io
  names:
    kind: Network
    listKind: NetworkList
    plural: networks
    singular: network
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: The Schema for the network API
          type: object
          properties:
            spec:
              description: NetworkSpec defines network resource
              type: object
              properties:
                adminStateUp:
                  type: boolean
                availabilityZoneHints:
                  type: string
                availabilityZones:
                  type: string
                createdAt:
                  type: string
                description:
                  type: string
                ID:
                  type: string
                IPv4AddressScope:
                  type: string
                IPv6AddressScope:
                  type: string
                mtu:
                  type: integer
                name:
                  type: string
                portSecurityEnabled:
                  type: string
                projectID:
                  type: string
                providerNetworkType:
                  type: string
                providerPhysicalNetwork:
                  type: string
                providerSegmentationID:
                  type: integer
                qosPolicyID:
                  type: string
                revisionNumber:
                  type: integer
                routerExternal:
                  type: boolean
                shared:
                  type: boolean
                status:
                  type: string
                subnets:
                  type: string
                tags:
                  type: array
                  items:
                    type: string
                tenantID:
                  type: string
                updatedAt:
                  type: string
                vlanTransparent:
                  type: boolean
              required:
                - name
